---
- name: Install Nginx
  package: name=nginx state=latest

- name: Create basic auth
  htpasswd: path="{{elk_nginx.auth}}" name="{{ elk_kibana.user }}" password="{{elk_kibana.password}}"

- name: Copy vhost template
  template: src=nginx-vhost.conf dest=/etc/nginx/sites-enabled/elk.conf
  notify: Restart Nginx 
