---
# handlers file for theShirbiny.elkserver
- name: Restart Nginx
  service: name=nginx state=restarted enabled=yes

- name: Restart Elasticsearch
  service: name=elasticsearch state=restarted enabled=yes

- name: Restart Logstash
  service: name=logstash state=restarted enabled=yes

- name: Restart Kibana
  service: name=kibana state=restarted enabled=yes
